name: Push Thyroid Recurrence Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements/requirements.txt
      - name: Train and save pipeline
        run: python recurrence_model/train_pipeline.py
      - uses: actions/upload-artifact@v2
        with:
          name: trained-pipeline
          path: recurrence_model/trained_models/*.pkl
          retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/download-artifact@v2
        with:
          name: trained-pipeline
          path: recurrence_model/trained_models
      - name: Install dependencies
        run: pip install -r requirements/test_requirements.txt
      - name: Test with pytest
        run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/download-artifact@v2
        with:
          name: trained-pipeline
          path: recurrence_model/trained_models
      - name: Install dependencies
        run: pip install --upgrade build
      - name: Build package
        run: python -m build
      - uses: actions/upload-artifact@v2
        with:
          name: build-package
          path: dist/*.whl
          retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: recurrence_api
      - name: Login to Docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker build . -f Dockerfile -t $DOCKER_USER/thyroid-recurrence-api:latest
      - name: Push Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker push $DOCKER_USER/thyroid-recurrence-api
      - name: Logout from Docker hub
        run: docker logout
